### ISSUE TITLE
Added the support GitHub Actions

### ISSUE THREAD

**Issue by obervinov** [obervinov/pyinstabot-downloader#10]
- [x]  **release.yml**

```yml
name: Create GitHub Release

on:
  push:
    branches: [main]
    paths: ['users/**']

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/create.release.yml@v1.0.4
    needs: [pylint, verify-package, verify-changelog, pytest]
```

- [x]  **tests.yml**
```yml
name: Tests and Checks

on:
  push:
    branches:    
      - '*'
      - '*/*'
      - '**'

jobs:
  pylint:
    uses: obervinov/_templates/.github/workflows/test.pylint.yml@v1.0.4
  verify-package:
    uses: obervinov/_templates/.github/workflows/verify.package.yml@v1.0.4
  verify-changelog:
    uses: obervinov/_templates/.github/workflows/verify.changelog.yml@v1.0.4
  pytest:
    uses: obervinov/_templates/.github/workflows/test.pytest-with-vault.yml@v1.0.4
```

- [x] **docker.yml**
