### ISSUE TITLE
GitHub  Actions: delete redundant jobs in the main branch b to make workflow more logical

### ISSUE THREAD

**Issue by obervinov** [obervinov/pyinstabot-downloader#23]
**Split workflow into three separate files for three different cases:**

- [ ] `pr`: all tests, linters and build a pr image for verification
```yaml
---
name: Test and Build PR

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'

env:
  # yamllint disable-line rule:line-length
  PROJECT_DESCRIPTION: "This project is a telegram bot that allows you to create backups of content from your Instagram profile to Dropbox or Mega clouds, as well as in the local file system."


jobs:
  pylint:
    uses: obervinov/_templates/.github/workflows/test.pylint.yml@v1.0.5
  verify-changelog:
    uses: obervinov/_templates/.github/workflows/verify.changelog.yml@v1.0.5
  build-release:
    uses: obervinov/_templates/.github/workflows/build.docker.yml@v1.0.5
    needs: [pylint, verify-changelog]
```
- [ ] `main`: creating a GH release
```yaml
---
name: Create GitHub Release

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/create.release.yml@v1.0.5

```
- [ ] `tag`: image assembly
```yaml
---
name: Build release image

# yamllint disable-line rule:truthy
on:
  create:
    tags:
      - "*"

env:
  # yamllint disable-line rule:line-length
  PROJECT_DESCRIPTION: "This project is a telegram bot that allows you to create backups of content from your Instagram profile to Dropbox or Mega clouds, as well as in the local file system."


jobs:
  build-release:
    uses: obervinov/_templates/.github/workflows/build.docker.yml@v1.0.5

```

or

```yaml
---
name: Tests and Checks

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  pylint:
    uses: obervinov/_templates/.github/workflows/test.pylint.yml@v1.0.5
  verify-package:
    uses: obervinov/_templates/.github/workflows/verify.package.yml@v1.0.5
  verify-changelog:
    uses: obervinov/_templates/.github/workflows/verify.changelog.yml@v1.0.5
  pytest:
    uses: obervinov/_templates/.github/workflows/test.pytest-with-vault.yml@v1.0.5


---
name: Create GitHub Release

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows: ["Tests and Checks"]
    branches: [main]
    types:
      - completed

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/create.release.yml@v1.0.5

```

**Fix names in Actions**
- [ ] fixed
![Image](https://user-images.githubusercontent.com/49606362/268446823-e3b476c4-8636-48e3-a955-49c8f1d707a6.png)
