### ISSUE TITLE
Rollback to old environment variable names PB_VAULT_APPROLE_ID PB_VAULT_APPROLE_SECRETID

### ISSUE THREAD

**Issue by obervinov** [obervinov/pyinstabot-downloader#27]
**Description**
Rollback to old environment variable names
- `PB_VAULT_APPROLE_ID` -> `VAULT_APPROLE_ID`
- `PB_VAULT_APPROLE_SECRETID`-> `VAULT_APPROLE_SECRETID`
For convenience of compatibility with deployment via terraform

**Sources**
- [x] https://github.com/obervinov/pyinstabot-downloader/blob/main/docker-compose.dev.yml#L34-L35
- [x] https://github.com/obervinov/pyinstabot-downloader/blob/main/docker-compose.release.yml#L11-L12
- [x] https://github.com/obervinov/pyinstabot-downloader/blob/main/docker-compose.prerelease.yml#L12-L13

**Usage example**
.env
```bash
VAULT_APPROLE_ID=myapproleid
VAULT_APPROLE_SECRETID=mysecretid
```

docker-compose.yml
```yaml
version: '3'
services:
  webapp:
    image: mywebapp
    environments:
      VAULT_APPROLE_ID=${VAULT_APPROLE_ID}
      VAULT_APPROLE_SECRETID=${VAULT_APPROLE_SECRETID}
    ports:
      - "8080:80"
    env_file:
      - .env
```
