### ISSUE TITLE
Add support env files in docker compose

### ISSUE THREAD

**Issue by obervinov** [obervinov/pyinstabot-downloader#28]
**Description**
Add support for external env files for the convenience of project deployment via terraform

**Sources**
- [ ] https://github.com/obervinov/pyinstabot-downloader/blob/main/docker-compose.dev.yml
- [ ] https://github.com/obervinov/pyinstabot-downloader/blob/main/docker-compose.release.yml
- [ ] https://github.com/obervinov/pyinstabot-downloader/blob/main/docker-compose.prerelease.yml

**Usage example**
.env
```bash
VAULT_APPROLE_ID=myapproleid
VAULT_APPROLE_SECRETID=mysecretid
```

docker-compose.yml
```yaml
version: '3'
services:
  webapp:
    image: mywebapp
    environments:
      VAULT_APPROLE_ID=${VAULT_APPROLE_ID}
      VAULT_APPROLE_SECRETID=${VAULT_APPROLE_SECRETID}
    ports:
      - "8080:80"
    env_file:
      - .env
```
